// Generated by https://quicktype.io

export default interface LoginResponseInfo {
    status: number;
    data:   Data;
}

export interface Data {
    name:    string;
    name_en: string;
    id:      number;
    subid:   number;
    dept:    string;
    dept_en: string;
}
